import { createContext, useContext, useState, ReactNode } from "react";

const translations: Record<string, Record<string, string>> = {
  en: {
    "nav.home": "Home",
    "nav.markets": "Markets",
    "nav.invest": "Invest",
    "nav.portfolio": "Portfolio",
    "nav.profile": "Profile",
    "nav.dashboard": "Dashboard",
    "nav.realestate": "Real Estate",
    "nav.retirement": "Retirement",
    "nav.adminDashboard": "Admin Dashboard",
    "nav.downloadApp": "Download App",
    "hero.title": "Invest Smarter. Grow Without Limits.",
    "hero.subtitle": "One platform for stocks, crypto, forex, real estate, and retirement. Build wealth with institutional-grade tools designed for everyone.",
    "hero.aiInsights": "Now with AI-Powered Portfolio Insights",
    "hero.getStarted": "Get Started Free",
    "hero.exploreMarkets": "Explore Markets",
    "categories.title": "Every Asset Class. One Platform.",
    "categories.subtitle": "Diversify across the world's most profitable markets from a single, high-performance dashboard.",
    "cta.title": "Ready to Build Your Wealth?",
    "cta.button": "Create Your Free Account",
    "auth.login": "Log In",
    "auth.signup": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.firstName": "First Name",
    "auth.lastName": "Last Name",
    "dashboard.welcome": "Welcome back",
    "dashboard.balance": "Portfolio Balance",
    "dashboard.aiInsights": "AI-Powered Insights",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.totalInvested": "Total Invested",
    "dashboard.totalEarned": "Total Earned",
    "dashboard.performing": "Your portfolio is performing",
    "dashboard.wellToday": "well today.",
    "dashboard.deposit": "Deposit",
    "dashboard.withdraw": "Withdraw",
    "dashboard.investNow": "Invest Now",
    "dashboard.connectWallet": "Connect Wallet",
    "dashboard.aiMessage": "\"Your portfolio is heavily weighted in stocks. Consider diversifying into crypto or real estate for better risk-adjusted returns.\"",
    "dashboard.optimization": "Optimization Strategy",
    "dashboard.liveMarket": "Live Market Analysis",
    "dashboard.allocation": "Asset Allocation",
    "dashboard.profitHistory": "Profit History",
    "dashboard.monthProfit": "+12.4% THIS MONTH",
    "dashboard.transactions": "Transactions",
    "dashboard.noActivity": "No recent activity found. Start investing to see your portfolio here.",
    "markets.all": "All",
    "markets.stocks": "Stocks",
    "markets.crypto": "Crypto",
    "markets.forex": "Forex",
    "markets.commodities": "Commodities",
    "markets.subtitle": "Explore global investment opportunities",
    "markets.search": "Search assets...",
    "markets.asset": "Asset",
    "markets.price": "Price",
    "markets.change": "24h Change",
    "markets.marketCap": "Market Cap / Volume",
    "realestate.title": "Real Estate",
    "realestate.subtitle": "Fractional ownership in premium properties",
    "realestate.investFrom": "Invest from",
    "realestate.funded": "Funded",
    "realestate.investNow": "Invest Now",
    "retirement.title": "Retirement Planner",
    "retirement.estimate": "Project your financial future with interactive tools",
    "retirement.monthlySavings": "Monthly Contribution",
    "retirement.yearsToRetirement": "Investment Period",
    "retirement.years": "years",
    "retirement.expectedReturn": "Expected Annual Return",
    "retirement.projectedValue": "Projected Future Value",
    "retirement.totalContributed": "Total contributed",
    "retirement.growthProjection": "Growth Projection",
    "retirement.suggestedPlans": "Suggested Plans",
    "retirement.selectPlan": "Select Plan",
    "settings.language": "Language",
    "settings.appearance": "Appearance",
    "settings.dark": "Dark",
    "settings.light": "Light",
    "settings.system": "System",
    "profile.personal": "Personal Information",
    "profile.personalDesc": "Update your details and account settings",
    "profile.security": "Security & Privacy",
    "profile.securityDesc": "Manage your password and 2FA",
    "profile.notifications": "Notifications",
    "profile.notificationsDesc": "Configure your alert preferences",
    "profile.payments": "Payment Methods",
    "profile.paymentsDesc": "Manage your bank accounts and cards",
    "profile.settings": "App Settings",
    "profile.settingsDesc": "Theme and language preferences",
    "profile.investorProfile": "Investor Profile",
    "profile.notSignedIn": "Not signed in",
    "profile.verifiedInvestor": "Verified Investor",
    "profile.logout": "Log Out",
    "footer.tagline": "The all-in-one investment ecosystem for modern investors.",
    "footer.products": "Products",
    "footer.company": "Company",
    "footer.legal": "Legal",
    "footer.about": "About",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.blog": "Blog",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",
    "footer.security": "Security",
    "footer.compliance": "Compliance",
    "footer.rights": "All rights reserved.",
    "nav.stocks": "Stocks",
    "nav.crypto": "Crypto",
    "nav.forex": "Forex",
  },
  es: {
    "nav.home": "Inicio",
    "nav.markets": "Mercados",
    "nav.invest": "Invertir",
    "nav.portfolio": "Portafolio",
    "nav.profile": "Perfil",
    "nav.dashboard": "Panel",
    "nav.realestate": "Bienes Raíces",
    "nav.retirement": "Jubilación",
    "nav.adminDashboard": "Panel de Admin",
    "nav.downloadApp": "Descargar App",
    "hero.title": "Invierte Más Inteligente. Crece Sin Límites.",
    "hero.subtitle": "Una plataforma para acciones, cripto, forex, bienes raíces y jubilación. Construye riqueza con herramientas de grado institucional diseñadas para todos.",
    "hero.getStarted": "Comienza Gratis",
    "hero.exploreMarkets": "Explorar Mercados",
    "categories.title": "Toda Clase de Activo. Una Plataforma.",
    "categories.subtitle": "Diversifica en los mercados más rentables del mundo desde un solo panel de alto rendimiento.",
    "cta.title": "¿Listo para Construir Tu Riqueza?",
    "cta.button": "Crea Tu Cuenta Gratis",
    "auth.login": "Iniciar Sesión",
    "auth.signup": "Registrarse",
    "auth.email": "Correo Electrónico",
    "auth.password": "Contraseña",
    "auth.firstName": "Nombre",
    "auth.lastName": "Apellido",
    "dashboard.welcome": "Bienvenido de nuevo",
    "dashboard.balance": "Balance del Portafolio",
    "dashboard.aiInsights": "Información con IA",
    "dashboard.recentActivity": "Actividad Reciente",
    "dashboard.totalInvested": "Total Invertido",
    "dashboard.totalEarned": "Total Ganado",
    "dashboard.performing": "Tu portafolio se está desempeñando",
    "dashboard.wellToday": "bien hoy.",
    "dashboard.deposit": "Depositar",
    "dashboard.withdraw": "Retirar",
    "dashboard.investNow": "Invertir Ahora",
    "dashboard.connectWallet": "Conectar Wallet",
    "dashboard.aiMessage": "\"Tu portafolio está muy inclinado hacia las acciones. Considera diversificar en cripto o bienes raíces para obtener mejores rendimientos ajustados al riesgo.\"",
    "dashboard.optimization": "Estrategia de Optimización",
    "dashboard.liveMarket": "Análisis de Mercado en Vivo",
    "dashboard.allocation": "Asignación de Activos",
    "dashboard.profitHistory": "Historial de Ganancias",
    "dashboard.monthProfit": "+12.4% ESTE MES",
    "dashboard.transactions": "Transacciones",
    "dashboard.noActivity": "No se encontró actividad reciente. Comienza a invertir para ver tu portafolio aquí.",
    "markets.all": "Todos",
    "markets.stocks": "Acciones",
    "markets.crypto": "Cripto",
    "markets.forex": "Forex",
    "markets.commodities": "Materias Primas",
    "markets.subtitle": "Explora oportunidades de inversión global",
    "markets.search": "Buscar activos...",
    "markets.asset": "Activo",
    "markets.price": "Precio",
    "markets.change": "Cambio 24h",
    "markets.marketCap": "Cap. de Mercado / Volumen",
    "realestate.title": "Bienes Raíces",
    "realestate.subtitle": "Propiedad fraccionada en propiedades premium",
    "realestate.investFrom": "Invertir desde",
    "realestate.funded": "Financiado",
    "realestate.investNow": "Invertir Ahora",
    "retirement.title": "Planificador de Jubilación",
    "retirement.estimate": "Proyecte su futuro financiero con herramientas interactivas",
    "retirement.monthlySavings": "Contribución Mensual",
    "retirement.yearsToRetirement": "Periodo de Inversión",
    "retirement.years": "años",
    "retirement.expectedReturn": "Rendimiento Anual Esperado",
    "retirement.projectedValue": "Valor Futuro Proyectado",
    "retirement.totalContributed": "Total aportado",
    "retirement.growthProjection": "Proyección de Crecimiento",
    "retirement.suggestedPlans": "Planes Sugeridos",
    "retirement.selectPlan": "Seleccionar Plan",
    "settings.language": "Idioma",
    "settings.appearance": "Apariencia",
    "settings.dark": "Oscuro",
    "settings.light": "Claro",
    "settings.system": "Sistema",
    "profile.personal": "Información Personal",
    "profile.personalDesc": "Actualiza tus detalles y ajustes de cuenta",
    "profile.security": "Seguridad y Privacidad",
    "profile.securityDesc": "Gestiona tu contraseña y 2FA",
    "profile.notifications": "Notificaciones",
    "profile.notificationsDesc": "Configura tus preferencias de alertas",
    "profile.payments": "Métodos de Pago",
    "profile.paymentsDesc": "Gestiona tus cuentas bancarias y tarjetas",
    "profile.settings": "Ajustes de la App",
    "profile.settingsDesc": "Preferencias de tema e idioma",
    "profile.investorProfile": "Perfil del Inversor",
    "profile.notSignedIn": "No has iniciado sesión",
    "profile.verifiedInvestor": "Inversor Verificado",
    "profile.logout": "Cerrar Sesión",
    "footer.tagline": "El ecosistema de inversión todo en uno para inversores modernos.",
    "footer.products": "Productos",
    "footer.company": "Empresa",
    "footer.legal": "Legal",
    "footer.about": "Sobre Nosotros",
    "footer.careers": "Carreras",
    "footer.press": "Prensa",
    "footer.blog": "Blog",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",
    "footer.security": "Seguridad",
    "footer.compliance": "Cumplimiento",
    "footer.rights": "Todos los derechos reservados.",
    "nav.stocks": "Acciones",
    "nav.crypto": "Cripto",
    "nav.forex": "Forex",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.markets": "Marchés",
    "nav.invest": "Investir",
    "nav.portfolio": "Portefeuille",
    "nav.profile": "Profil",
    "nav.dashboard": "Tableau de bord",
    "nav.realestate": "Immobilier",
    "nav.retirement": "Retraite",
    "nav.adminDashboard": "Tableau de bord Admin",
    "nav.downloadApp": "Télécharger l'App",
    "hero.title": "Investissez Plus Intelligemment. Grandissez Sans Limites.",
    "hero.subtitle": "Une plateforme pour les actions, la crypto, le forex, l'immobilier et la retraite. Construisez votre patrimoine avec des outils institutionnels conçus pour tous.",
    "hero.getStarted": "Commencer Gratuitement",
    "hero.exploreMarkets": "Explorer les Marchés",
    "categories.title": "Toutes Classes d'Actifs. Une Plateforme.",
    "categories.subtitle": "Diversifiez sur les marchés les plus rentables du monde depuis un tableau de bord haute performance.",
    "cta.title": "Prêt à Construire Votre Patrimoine ?",
    "cta.button": "Créer Votre Compte Gratuit",
    "auth.login": "Connexion",
    "auth.signup": "S'inscrire",
    "auth.email": "E-mail",
    "auth.password": "Mot de passe",
    "auth.firstName": "Prénom",
    "auth.lastName": "Nom",
    "dashboard.welcome": "Bon retour",
    "dashboard.balance": "Solde du Portefeuille",
    "dashboard.aiInsights": "Analyses par IA",
    "dashboard.recentActivity": "Activité Récente",
    "dashboard.totalInvested": "Total Investi",
    "dashboard.totalEarned": "Total Gagné",
    "dashboard.performing": "Votre portefeuille se porte",
    "dashboard.wellToday": "bien aujourd'hui.",
    "dashboard.deposit": "Dépôt",
    "dashboard.withdraw": "Retrait",
    "dashboard.investNow": "Investir Maintenant",
    "dashboard.connectWallet": "Connecter Wallet",
    "dashboard.aiMessage": "\"Votre portefeuille est fortement pondéré en actions. Envisagez de diversifier dans la crypto ou l'immobilier pour de meilleurs rendements ajustés au risque.\"",
    "dashboard.optimization": "Stratégie d'Optimisation",
    "dashboard.liveMarket": "Analyse du Marché en Direct",
    "dashboard.allocation": "Allocation d'Actifs",
    "dashboard.profitHistory": "Historique des Profits",
    "dashboard.monthProfit": "+12.4% CE MOIS",
    "dashboard.transactions": "Transactions",
    "dashboard.noActivity": "Aucune activité récente trouvée. Commencez à investir pour voir votre portefeuille ici.",
    "markets.all": "Tous",
    "markets.stocks": "Actions",
    "markets.crypto": "Crypto",
    "markets.forex": "Forex",
    "markets.commodities": "Matières Premières",
    "markets.subtitle": "Explorez les opportunités d'investissement mondiales",
    "markets.search": "Rechercher des actifs...",
    "markets.asset": "Actif",
    "markets.price": "Prix",
    "markets.change": "Variation 24h",
    "markets.marketCap": "Cap. Boursière / Volume",
    "realestate.title": "Immobilier",
    "realestate.subtitle": "Propriété fractionnée dans des propriétés de prestige",
    "realestate.investFrom": "Investir à partir de",
    "realestate.funded": "Financé",
    "realestate.investNow": "Investir Maintenant",
    "retirement.title": "Planificateur de Retraite",
    "retirement.estimate": "Projetez votre avenir financier avec des outils interactifs",
    "retirement.monthlySavings": "Contribution Mensuelle",
    "retirement.yearsToRetirement": "Période d'Investissement",
    "retirement.years": "ans",
    "retirement.expectedReturn": "Rendement Annuel Attendu",
    "retirement.projectedValue": "Valeur Future Projetée",
    "retirement.totalContributed": "Total contribué",
    "retirement.growthProjection": "Projection de Croissance",
    "retirement.suggestedPlans": "Plans Suggérés",
    "retirement.selectPlan": "Sélectionner le Plan",
    "settings.language": "Langue",
    "settings.appearance": "Apparence",
    "settings.dark": "Sombre",
    "settings.light": "Clair",
    "settings.system": "Système",
    "profile.personal": "Informations Personnelles",
    "profile.personalDesc": "Mettez à jour vos coordonnées et paramètres",
    "profile.security": "Sécurité et Confidentialité",
    "profile.securityDesc": "Gérez votre mot de passe et la 2FA",
    "profile.notifications": "Notifications",
    "profile.notificationsDesc": "Configurez vos préférences d'alerte",
    "profile.payments": "Méthodes de Paiement",
    "profile.paymentsDesc": "Gérez vos comptes bancaires et cartes",
    "profile.settings": "Paramètres de l'App",
    "profile.settingsDesc": "Préférences de thème et de langue",
    "profile.investorProfile": "Profil de l'Investisseur",
    "profile.notSignedIn": "Non connecté",
    "profile.verifiedInvestor": "Investisseur Vérifié",
    "profile.logout": "Déconnexion",
  },
  de: {
    "nav.home": "Startseite",
    "nav.markets": "Märkte",
    "nav.invest": "Investieren",
    "nav.portfolio": "Portfolio",
    "nav.profile": "Profil",
    "hero.title": "Smarter Investieren. Grenzenlos Wachsen.",
    "hero.subtitle": "Eine Plattform für Aktien, Krypto, Forex, Immobilien und Altersvorsorge. Vermögen aufbauen mit professionellen Tools für jeden.",
    "hero.getStarted": "Kostenlos Starten",
    "hero.exploreMarkets": "Märkte Erkunden",
    "categories.title": "Jede Anlageklasse. Eine Plattform.",
    "categories.subtitle": "Diversifizieren Sie über die profitabelsten Märkte der Welt von einem einzigen Hochleistungs-Dashboard.",
    "cta.title": "Bereit Ihr Vermögen Aufzubauen?",
    "cta.button": "Kostenloses Konto Erstellen",
    "auth.login": "Anmelden",
    "auth.signup": "Registrieren",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.firstName": "Vorname",
    "auth.lastName": "Nachname",
    "dashboard.welcome": "Willkommen zurück",
    "dashboard.balance": "Portfolio-Saldo",
    "settings.language": "Sprache",
    "settings.appearance": "Erscheinungsbild",
    "settings.dark": "Dunkel",
    "settings.light": "Hell",
    "settings.system": "System",
  },
  it: {
    "nav.home": "Home",
    "nav.markets": "Mercati",
    "nav.invest": "Investi",
    "nav.portfolio": "Portafoglio",
    "nav.profile": "Profilo",
    "hero.title": "Investi in modo più intelligente. Cresci senza limiti.",
    "hero.subtitle": "Un'unica piattaforma per azioni, cripto, forex, immobiliare e pensione. Costruisci ricchezza con strumenti di livello istituzionale progettati per tutti.",
    "hero.getStarted": "Inizia gratuitamente",
    "hero.exploreMarkets": "Esplora i mercati",
    "categories.title": "Ogni classe di attività. Un'unica piattaforma.",
    "categories.subtitle": "Diversifica nei mercati più redditizi del mondo da un'unica dashboard ad alte prestazioni.",
    "cta.title": "Pronto a costruire la tua ricchezza?",
    "cta.button": "Crea il tuo account gratuito",
    "auth.login": "Accedi",
    "auth.signup": "Iscriviti",
    "auth.email": "E-mail",
    "auth.password": "Password",
    "auth.firstName": "Nome",
    "auth.lastName": "Cognome",
    "dashboard.welcome": "Bentornato",
    "dashboard.balance": "Saldo del portafoglio",
    "settings.language": "Lingua",
    "settings.appearance": "Aspetto",
    "settings.dark": "Scuro",
    "settings.light": "Chiaro",
    "settings.system": "Sistema",
  },
  pt: {
    "nav.home": "Início",
    "nav.markets": "Mercados",
    "nav.invest": "Investir",
    "nav.portfolio": "Portfólio",
    "nav.profile": "Perfil",
    "hero.title": "Invista de forma mais inteligente. Cresça sem limites.",
    "hero.subtitle": "Uma única plataforma para ações, cripto, forex, imobiliário e reforma. Construa riqueza com ferramentas de nível institucional projetadas para todos.",
    "hero.getStarted": "Comece gratuitamente",
    "hero.exploreMarkets": "Explorar mercados",
    "categories.title": "Cada classe de ativos. Uma plataforma.",
    "categories.subtitle": "Diversifique nos mercados mais lucrativos do mundo a partir de um único painel de alto desempenho.",
    "cta.title": "Pronto para construir sua riqueza?",
    "cta.button": "Crie sua conta gratuita",
    "auth.login": "Entrar",
    "auth.signup": "Cadastrar-se",
    "auth.email": "E-mail",
    "auth.password": "Senha",
    "auth.firstName": "Nome",
    "auth.lastName": "Sobrenome",
    "dashboard.welcome": "Bem-vindo de volta",
    "dashboard.balance": "Saldo do portfólio",
    "settings.language": "Idioma",
    "settings.appearance": "Aparência",
    "settings.dark": "Escuro",
    "settings.light": "Claro",
    "settings.system": "Sistema",
  },
};

interface LanguageContextType {
  lang: string;
  setLang: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "en",
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState(() => localStorage.getItem("app-lang") || "en");

  const setLang = (newLang: string) => {
    setLangState(newLang);
    localStorage.setItem("app-lang", newLang);

    // Force Google Translate to update
    const updateGoogleTranslate = () => {
      // Set the googtrans cookie which Google Translate uses
      const domain = window.location.hostname;
      const cookieValue = `/en/${newLang}`;
      document.cookie = `googtrans=${cookieValue}; path=/`;
      document.cookie = `googtrans=${cookieValue}; domain=.${domain}; path=/`;

      const googleTranslateDropdown = document.querySelector(".goog-te-combo") as HTMLSelectElement;
      if (googleTranslateDropdown) {
        googleTranslateDropdown.value = newLang;
        googleTranslateDropdown.dispatchEvent(new Event("change"));
        return true;
      }
      return false;
    };

    if (!updateGoogleTranslate()) {
      // If not found, try again a few times
      let attempts = 0;
      const interval = setInterval(() => {
        attempts++;
        if (updateGoogleTranslate() || attempts > 10) {
          clearInterval(interval);
        }
      }, 500);
    }
  };

  const t = (key: string) => translations[lang]?.[key] || translations.en?.[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
